[project]
id = "tpfapoyqovljtkzxbykd"

[api]
schemas = ["public", "knowledge_share_hub", "storage", "graphql_public"]
extra_search_path = ["public", "knowledge_share_hub", "extensions"]

[auth]
site_url = "http://localhost:8080"
additional_redirect_urls = ["https://localhost:8080"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
